defaults: &DEFAULTS
  max_score: 10.0
  min_indicators: 10
  gdp_data_file: "ny.gdp.pcap.cd_Indicator_MetaData_en_EXCEL.csv"
  twitter_consumer_key: "XPTwGgP12RqGpf3csNUZgA"
  twitter_consumer_secret: "KDL1fxgc1VYgOswj2r01R0RGbjlV0YeVcGZhI7EIA9o"
  twitter_access_token: "7661012-gEe5gFhF9M9GkPFf1zH7tGpYSac8kzXsMjxpzKSPkQ"
  twitter_access_token_secret: "NBOqdlsnXPNg1eR5iLe7ZMzgnEn174Jx4JtRfy2yY72gM"

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS
  max_score: 10.0
  min_indicators: 3

production:
  <<: *DEFAULTS
